config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    authenticated do
      root to: 'websites#index', as: :authenticated_root
    end
  end

  root to: 'welcome#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    passwords: 'users/passwords'
  }, path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up'
  }

  namespace(:api) do
    namespace(:v1) do
      resources(:websites, only: %w(index create))
    end
  end

  resource(:settings, only: %w(edit update))

  resources(:tokens, only: %w(index new create destroy))

  resources(:users, only: %w(index destroy))

  namespace(:users) do
    namespace(:invitations) do
      resources(:instructions, only: %w(index))
    end

    namespace(:passwords) do
      resources(:instructions, only: %w(index))
    end
  end

  resources(:websites) do
    scope(module: :websites) do
      namespace(:charts) do
        resources(:response_time, only: %w(index), path: 'response-time')
      end
    end
  end
end

app/models/website.rb
# frozen_string_literal: true

# Website
class Website < ApplicationRecord
  include Paginatable

  VALID_URL_REGEX = /\A#{URI::regexp(['http', 'https'])}\z/

  has_many :pings, dependent: :delete_all
  has_many :recent_pings, -> { order(created_at: :desc).limit(5) }, class_name: 'Ping'
  has_many :daily_pings, -> { limit(1_440) }, class_name: 'Ping'

  # Only query the max number from pagination.
  has_many :paginatable_pings, -> { limit(360) }, class_name: 'Ping'

  validates(:name, presence: true)
  validates(:url, presence: true, format: { with: VALID_URL_REGEX })

  before_create(:set_ssl)
  after_commit(:create_ping, on: :create)
  after_commit(:check_pinger_job, on: :update, if: :saved_change_to_active?)

  scope(:active, -> { where(active: true) })

  def basic_auth?
    [basic_auth_username, basic_auth_password].all?(&:present?)
  end

  def job
    Delayed::Job.where('handler LIKE ?', "%Website/#{id}%").first
  end

  private

  def set_ssl
    self.ssl = URI(url).scheme == 'https'
  rescue
    self.ssl = false
  end

  def create_ping
    PingerJob.perform_later(self)
  end

  def check_pinger_job
    if active?
      create_ping
    else
      job.destroy if job.present?
    end
  end
end

app/controllers/api/v1/websites_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class WebsitesController < BaseController
      def index
        render(
          json: Website.active.decorate,
          each_serializer: WebsiteSerializer
        )
      end

      def create
        @website = Website.new(website_params)

        if @website.save
          respond_with @website, status: 201
        else
          respond_with @website, status: 400
        end
      end

      private

      def website_params
        params.require(:website).permit(
          :name, :url, :basic_auth_username, :basic_auth_password,
          :active, :aws_instance_id, :aws_region
        )
      end
    end
  end
end

app/controllers/websites/base_controller.rb
# frozen_string_literal: true

module Websites
  # BaseController
  class BaseController < ApplicationController
    before_action(:set_website)

    private

    def set_website
      @website = Website.find(params[:website_id])
    end
  end
end

app/controllers/websites/charts/response_time_controller.rb
# frozen_string_literal: true

module Websites
  module Charts
    # ResponseTimeController
    class ResponseTimeController < Websites::BaseController
      def index
        respond_to do |format|
          format.html
          format.json do
            @data = ::Charts::ResponseTime.new(
              @website.daily_pings.without_outliers
            ).aggregate
            render json: @data
          end
        end
      end
    end
  end
end

app/controllers/websites_controller.rb
# frozen_string_literal: true

# WebsitesController
class WebsitesController < ApplicationController
  include PaginatableConcern

  before_action(:set_website, only: %w(show edit update destroy))

  def index
    @websites = Website.paginate(params).decorate

    respond_to do |format|
      format.html
      format.json { return_paginated_resource }
    end
  end

  def new
    @website = Website.new
  end

  def create
    @website = Website.new(website_params)

    if @website.save
      flash[:success] = t('.success', name: @website.name)
      redirect_to(root_path)
    else
      render(:new)
    end
  end

  def show
    @pings = @website.paginatable_pings.paginate(params).decorate
  end

  def edit; end

  def update
    if @website.update(website_params)
      flash[:success] = t('.success', name: @website.name)
      redirect_to(root_path)
    else
      render(:edit)
    end
  end

  def destroy
    WebsiteDestroyerJob.perform_later(@website)
    flash[:success] = t('.success', name: @website.name)
    redirect_to(root_path)
  end

  private

  def set_website
    @website = Website.find(params[:id])
  end

  def website_params
    params.require(:website).permit(
      :name, :url, :basic_auth_username, :basic_auth_password,
      :active, :aws_instance_id, :aws_region
    )
  end
end

app/helpers/websites_helper.rb
# frozen_string_literal: true

module WebsitesHelper
  def options_for_aws_region(selected = nil)
    options_for_select(aws_regions, selected)
  end

  def aws_regions
    # http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/
    # using-regions-availability-zones.html#concepts-available-regions
    [
      ['US East (N. Virginia) · us-east-1', 'us-east-1'],
      ['US East (Ohio) · us-east-2', 'us-east-2'],
      ['US West (N. California) · us-west-1', 'us-west-1'],
      ['US West (Oregon) · us-west-2', 'us-west-2'],
      ['Canada (Central) · ca-central-1', 'ca-central-1'],
      ['EU (Ireland) · eu-west-1', 'eu-west-1'],
      ['EU (London) · eu-west-1', 'eu-west-2'],
      ['EU (Frankfurt) · eu-central-1', 'eu-central-1'],
      ['Asia Pacific (Tokyo) · ap-northeast-1', 'ap-northeast-1'],
      ['Asia Pacific (Seoul) · ap-northeast-2', 'ap-northeast-2'],
      ['Asia Pacific (Singapore) · ap-southeast-1', 'ap-southeast-1'],
      ['Asia Pacific (Mumbai) · ap-south-1', 'ap-south-1'],
      ['South America (São Paulo) · sa-east-1', 'sa-east-1']
    ]
  end
end

app/views/websites/_form.html.erb
<%= form_for(website) do |f| %>
  <div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name,
      autofocus: true, autocomplete: :off,
      class: "form-control") %>
    <%= error_message_on(f.object, :name) %>
  </div>

  <div class="form-group">
    <%= f.label(:url, t('.url')) %>
    <%= f.url_field(:url, class: "form-control") %>
    <%= error_message_on(f.object, :url) %>
  </div>

  <div class="form-check">
    <%= f.check_box(:active, class: "form-check-input") %>
    <%= f.label(:active, t('.active'), class: "form-check-label") %>
    <%= error_message_on(f.object, :active) %>
  </div>

  <div class="hr-sect"><%= t('.optional') %></div>

  <div class="form-group">
    <%= f.label(:basic_auth_username) %>
    <%= f.text_field(:basic_auth_username, class: "form-control") %>
    <%= error_message_on(f.object, :basic_auth_username) %>
  </div>

  <div class="form-group">
    <%= f.label(:basic_auth_password) %>
    <%= f.text_field(:basic_auth_password, class: "form-control") %>
    <%= error_message_on(f.object, :basic_auth_password) %>
  </div>

  <% if (Setting.global.present? &&
      (Setting.global.aws_key.present? && Setting.global.aws_secret.present?)) %>
    <div class="hr-sect"><%= t('.aws_info') %></div>

    <div class="form-group">
      <%= f.label(:aws_instance_id, t('.aws_instance_id')) %>
      <%= f.text_field(:aws_instance_id, class: "form-control") %>
      <%= error_message_on(f.object, :aws_instance_id) %>
    </div>

    <div class="form-group">
      <%= f.label(:aws_region, t('.aws_region')) %>
      <%= f.select(:aws_region,
        options_for_aws_region(f.object.aws_region),
         { prompt: t('.aws_region_select') },
         { class: "form-control" }) %>
      <%= error_message_on(f.object, :aws_region) %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/websites/_next_page.html.erb
<% unless websites.last_page? %>
  <button class="btn btn-primary btn-block mb-4"
    data-url="<%= websites_url(page: websites.next_page) %>"
    data-behavior="load-more">
    <%= t('.load_more') %>
  </button>
<% end %>

app/views/websites/_sliced.html.erb
<% websites.each_slice(3) do |websites| %>
  <div class="row">
    <%= render(websites) %>
  </div>
<% end %>

app/views/websites/_website.html.erb
<div class="col-lg-4 col-md-12">
  <%= link_to(website_path(website), class: "card card-link mb-3") do %>
    <div class="card-body">
      <h5 class="card-title mb-0">
        <% unless website.active? %>
          <small class="badge badge-secondary lh-1 float-right">Inactive</small>
        <% end %>

        <%= website.name %>
      </h5>

      <div class="hr-sect">Recent Pings</div>

      <%= render(website.recent_pings) %>
    </div>
  <% end %>
</div>

app/views/websites/edit.html.erb
<div class="page-header">
  <h4 class="page-title"><%= t(".title", website_name: @website.name) %></h4>
  <h5 class="page-subtitle"><%= t(".subtitle") %></h5>

  <div class="page-actions">
    <%= link_to(t('.back', website_name: @website.name), website_path(@website),
      class: "btn btn-secondary btn-sm") %>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card card-body mb-3">
      <%= render("form", website: @website) %>
    </div>
  </div>
</div>

app/views/websites/index.html.erb
<div class="page-header">
  <h4 class="page-title"><%= t(".title") %></h4>
  <h5 class="page-subtitle"><%= t(".subtitle") %></h5>

  <div class="page-actions">
    <%= link_to(t('.add'), new_website_path, class: "btn btn-primary btn-sm") %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @websites.any? %>
      <div data-behavior="websites-list">
        <%= render("websites/sliced", websites: @websites) %>
      </div>

      <div class="row">
        <div class="col-lg-4 offset-lg-4 col-md-6 offset-md-3">
          <div class="text-center" data-behavior="pagination-wrapper">
            <%= render("websites/next_page", websites: @websites) %>
          </div>
        </div>
      </div>
    <% else %>
      <%= render("shared/blankslate", resource: t('.resource')) %>
    <% end %>
  </div>
</div>

app/views/websites/new.html.erb
<div class="page-header">
  <h4 class="page-title"><%= t(".title") %></h4>
  <h5 class="page-subtitle"><%= t(".subtitle") %></h5>

  <div class="page-actions">
    <%= link_to(t('.back'), websites_path, class: "btn btn-secondary btn-sm") %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card card-body mb-3">
      <%= render("form", website: @website) %>
    </div>
  </div>
</div>

app/views/websites/show.html.erb
<div class="page-header">
  <h4 class="page-title"><%= @website.name %></h4>
  <h5 class="page-subtitle"><%= t(".subtitle") %></h5>

  <div class="page-actions">
    <%= link_to(t('.response_times'), website_charts_response_time_index_path(@website),
      class: "btn btn-primary btn-sm") %>

    <%= link_to(t('.edit'), edit_website_path(@website),
      class: "btn btn-secondary btn-sm") %>

    <%= link_to(t('.destroy'), website_path(@website),
      method: :delete, data: { prompt: t('.destroy_confirm', name: @website.name) },
      class: "btn btn-outline-danger btn-sm") %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @pings.any? %>
      <div class="card card-body mb-3" data-behavior="pings-list">
        <%= render(partial: 'pings/ping', collection: @pings, as: :ping) %>
      </div>

      <div class="d-flex justify-content-center" data-behavior="pagination-wrapper">
        <%= paginate(@pings) %>
      </div>
    <% else %>
      <%= render("shared/blankslate", resource: t('.resource')) %>
    <% end %>
  </div>
</div>