config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    authenticated do
      root to: 'websites#index', as: :authenticated_root
    end
  end

  root to: 'welcome#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    passwords: 'users/passwords'
  }, path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up'
  }

  namespace(:api) do
    namespace(:v1) do
      resources(:websites, only: %w(index create))
    end
  end

  resource(:settings, only: %w(edit update))

  resources(:tokens, only: %w(index new create destroy))

  resources(:users, only: %w(index destroy))

  namespace(:users) do
    namespace(:invitations) do
      resources(:instructions, only: %w(index))
    end

    namespace(:passwords) do
      resources(:instructions, only: %w(index))
    end
  end

  resources(:websites) do
    scope(module: :websites) do
      namespace(:charts) do
        resources(:response_time, only: %w(index), path: 'response-time')
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise(
    :invitable, :database_authenticatable, :registerable,
    :rememberable, :trackable, :validatable, :recoverable
  )

  # alias the Devise Invitable method to check if a user is pending creation.
  alias_method(:pending?, :valid_invitation?)

  has_many(:tokens, foreign_key: :created_by_id, dependent: :destroy)

  def reset_password_token!
    set_reset_password_token # devise method
  end
end

app/controllers/users/invitations/instructions_controller.rb
# frozen_string_literal: true

module Users
  module Invitations
    # InstructionsController
    class InstructionsController < ApplicationController
      def index
        @user = User.find(params[:id])
      end
    end
  end
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

module Users
  # InvitationsController
  class InvitationsController < Devise::InvitationsController
    private

    def invite_resource(&block)
      # instance method, invite!, returns a User instance
      resource_class.invite!(
        invite_params.merge(skip_invitation_params),
        current_inviter,
        &block
      )
    end

    def after_invite_path_for(_inviter, invitee)
      users_invitations_instructions_path(
        id: invitee.id,
        token: invitee.raw_invitation_token
      )
    end

    def skip_invitation_params
      {
        skip_invitation: true # don't send an email.
      }
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  # PasswordsController
  class PasswordsController < Devise::PasswordsController
    skip_before_action(:require_no_authentication, only: %w(create))
    before_action(:authenticate_user!, only: %w(create))
    before_action(:set_user, only: %w(create))

    layout('unauthenticated', only: %w(edit update))

    def create
      if @token = @user.reset_password_token!
        redirect_to(after_sending_reset_password_instructions_path_for(@user))
      else
        flash[:danger] = t('.create.fail')
        redirect_back(fallback_location: users_path)
      end
    end

    def edit
      super
    end

    private

    def authenticate_user!
      warden.authenticate!
    end

    def set_user
      @user = User.find_by!(email: params[:user][:email])
    end

    def after_sending_reset_password_instructions_path_for(user)
      users_passwords_instructions_path(
        id: user.id,
        token: @token
      )
    end

    def after_resetting_password_path_for(_resource)
      root_path
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  # RegistrationsController
  class RegistrationsController < Devise::RegistrationsController
    before_action(:disable_registration, if: :account_setup?)

    def new
      super
    end

    private

    def account_setup?
      User.any?
    end

    def disable_registration
      flash[:warning] = t('.disable_registration')
      redirect_to(new_user_session_path)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  # SessionsController
  class SessionsController < Devise::SessionsController
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action(:set_user, only: %w(destroy))

  def index
    @users = User.decorate
  end

  def destroy
    @user.destroy

    flash[:success] = t('.success', email: @user.email)
    redirect_back(fallback_location: users_path)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<tr>
  <td><%= user.email %></td>

  <td><%= user.formatted_time(:created_at) %></td>

  <td>
    <span class="badge badge-<%= user.pending? ? 'secondary' : 'success' %>">
      <%= user.member_status_text %>
    </span>
  </td>

  <td class="text-right">
    <% if user.pending? %>
      <%= form_for(
        user,
        as: :user,
        url: invitation_path(:user),
        html: { class: "d-inline-block align-middle", method: :post }
      ) do |f| %>
        <%= f.hidden_field(:email, value: f.object.email) %>
        <%= button_tag(class: "btn btn-link btn-sm icon-15",
          title: t('.invitation_link'),
          data: { toggle: "tooltip", placement: "top-right" },
          type: "submit") do %>
          <i data-feather="mail"></i>
        <% end %>
      <% end %>
    <% end %>

    <%= form_for(
      user,
      as: :user,
      url: password_path(:user),
      html: { class: "d-inline-block align-middle", method: :post }) do |f| %>
      <%= f.hidden_field(:email, value: f.object.email) %>
      <%= button_tag(class: "btn btn-link btn-sm icon-15",
        title: t('.reset_password'),
        data: { toggle: "tooltip", placement: "top-right" },
        type: "submit") do %>
        <i data-feather="lock"></i>
      <% end %>
    <% end %>

    <% unless current_user.eql?(user) %>
      <div class="d-inline-block align-middle">
        <%= link_to(user_url(user),
          class: "btn btn-link btn-sm icon-15 text-danger",
          method: :delete, title: t('.destroy_link'),
          data: {
            toggle: "tooltip",
            placement: "top-right",
            prompt: t('.destroy_confirm', email: user.email)
          }
        ) do %>
          <i data-feather="trash" class="pointerless"></i>
        <% end %>
      </div>
    <% end %>
  </td>
</tr>

app/views/users/index.html.erb
<div class="page-header">
  <h4 class="page-title"><%= t(".title") %></h4>
  <h5 class="page-subtitle"><%= t(".subtitle") %></h5>

  <div class="page-actions">
    <%= link_to(t('.invite'), new_user_invitation_path, class: "btn btn-primary btn-sm") %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <div class="card card-body mb-3">
      <div class="table-responsive">
        <table class="table table-border-around mb-0">
          <thead>
            <tr>
              <th><%= t('.email') %></th>
              <th><%= t('.created_on') %></th>
              <th><%= t('.status') %></th>
              <th style="min-width: 140px;"></th>
            </tr>
          </thead>
          <tbody>
            <%= render(@users) %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>