config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    authenticated do
      root to: 'websites#index', as: :authenticated_root
    end
  end

  root to: 'welcome#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    passwords: 'users/passwords'
  }, path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up'
  }

  namespace(:api) do
    namespace(:v1) do
      resources(:websites, only: %w(index create))
    end
  end

  resource(:settings, only: %w(edit update))

  resources(:tokens, only: %w(index new create destroy))

  resources(:users, only: %w(index destroy))

  namespace(:users) do
    namespace(:invitations) do
      resources(:instructions, only: %w(index))
    end

    namespace(:passwords) do
      resources(:instructions, only: %w(index))
    end
  end

  resources(:websites) do
    scope(module: :websites) do
      namespace(:charts) do
        resources(:response_time, only: %w(index), path: 'response-time')
      end
    end
  end
end

app/views/shared/_blankslate.html.erb
<div class="blankslate">
  <h4 class="blankslate-title">
    <%= t('.title', resource: resource.pluralize) %>
  </h4>

  <% if yield.present? %>
    <div class="mt-4">
      <%= yield %>
    </div>
  <% end %>
</div>

app/views/shared/_browse-happy.html.erb
<!--[if lte IE 9]>
  <div class="browse-happy alert alert-info rounded-0 mb-0" role="alert">
    <%= sanitize(t('.text')) %>
  </div>
<![endif]-->

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-app">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="text-center py-5">
      <%= link_to("https://twitter.com/ProctorUEng", class: "footer-link",
        target: "_blank") do %>
        <%= image_tag("https://s3-us-west-2.amazonaws.com/storm-app/proctoru-open-source.svg",
          class: "footer-logo mb-3") %>
      <% end %>

      <ul class="list-inline mb-0">
        <li class="list-inline-item">
          <%= link_to("GitHub", "https://github.com/ProctorU/Storm",
            class: "text-muted", target: "_blank") %>
        </li>
        <li class="list-inline-item">&middot;</li>
        <li class="list-inline-item">
          <%= link_to("Twitter", "https://twitter.com/ProctorUEng",
            class: "text-muted", target: "_blank") %>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_meta-tags.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128" />
<meta name="application-name" content="Storm"/>
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="/mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="/mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="/mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="/mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="/mstile-310x310.png" />

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-lg bg-white">
  <div class="container">
    <div class="navbar-collapse">
      <%= link_to(root_path, class: "navbar-brand") do %>
        <%= image_tag("bolt.png", height: 26, alt: "Storm logo") %>
        <span class="ml-2 h5">Storm</span>
      <% end %>

      <ul class="navbar-nav ml-auto">
        <%= nav_link(t('.websites'), root_path) %>
        <%= nav_link(t('.settings'), edit_settings_path) %>
        <%= nav_link(t('.users'), users_path) %>
        <%= nav_link(t('.tokens'), tokens_path) %>
        <% if user_signed_in? %>
          <%= nav_link(t('.sign_out'), destroy_user_session_path, method: :delete) %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>