config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_scope :user do
    authenticated do
      root to: 'websites#index', as: :authenticated_root
    end
  end

  root to: 'welcome#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    passwords: 'users/passwords'
  }, path_names: {
    sign_in: 'sign-in',
    sign_out: 'sign-out',
    sign_up: 'sign-up'
  }

  namespace(:api) do
    namespace(:v1) do
      resources(:websites, only: %w(index create))
    end
  end

  resource(:settings, only: %w(edit update))

  resources(:tokens, only: %w(index new create destroy))

  resources(:users, only: %w(index destroy))

  namespace(:users) do
    namespace(:invitations) do
      resources(:instructions, only: %w(index))
    end

    namespace(:passwords) do
      resources(:instructions, only: %w(index))
    end
  end

  resources(:websites) do
    scope(module: :websites) do
      namespace(:charts) do
        resources(:response_time, only: %w(index), path: 'response-time')
      end
    end
  end
end

app/models/setting.rb
# frozen_string_literal: true

class Setting < ApplicationRecord
  attr_encrypted(
    :aws_key,
    key: Rails.application.secrets.secret_key_base.byteslice(0, 32)
  )
  attr_encrypted(
    :aws_secret,
    key: Rails.application.secrets.secret_key_base.byteslice(0, 32)
  )

  before_create :validate_only_one_setting_record

  def self.global
    first
  end

  private

  def validate_only_one_setting_record
    errors.add(:base, I18n.t('base.one_setting')) if Setting.count.positive?
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action(:create_settings, only: %w(edit))

  def edit
    @setting = Setting.first
  end

  def update
    @setting = Setting.first

    if @setting.update(setting_params)
      flash[:success] = t('.success')
      redirect_to edit_settings_path
    else
      render :edit
    end
  end

  private

  def setting_params
    params.require(:setting).permit(:aws_key, :aws_secret, :slack_url, :email_address)
  end

  def create_settings
    SettingsCreator.execute
  end
end

app/views/settings/_form.html.erb
<%= form_for(setting, url: settings_path) do |f| %>
  <div class="form-group">
    <%= f.label :slack_url, t('.labels.slack_url') %>
    <%= f.text_field :slack_url, autofocus: true, class: "form-control" %>
    <%= error_message_on(f.object, :slack_url) %>

    <p class="form-text text-muted">
      <%= t('.slack_instructions') %>
      <%= link_to t('.slack_action'),
        "https://slack.com/apps/A0F7XDUAZ-incoming-webhooks",
        target: :blank %>.
    </p>
  </div>

  <div class="form-group">
    <%= f.label :email_address, t('.labels.email_address') %>
    <%= f.text_field :email_address, autofocus: true, class: "form-control" %>
    <%= error_message_on(f.object, :email_address) %>
  </div>

  <div class="hr-sect"><%= t('.aws_section') %></div>

  <small class="d-block mb-3 text-muted"><%= t('.aws_info') %></small>

  <div class="form-group">
    <%= f.label :aws_key, t('.labels.aws_key') %>
    <%= f.text_field :aws_key, class: "form-control" %>
    <%= error_message_on(f.object, :aws_key) %>
  </div>

  <div class="form-group">
    <%= f.label :aws_secret, t('.labels.aws_secret') %>
    <%= f.text_field :aws_secret, class: "form-control" %>
    <%= error_message_on(f.object, :aws_secret) %>

    <p class="form-text text-muted">
      <%= t('.aws_instructions') %>
      <%= link_to t('.aws_action'), "#" %>.
    </p>
  </div>

  <div class="form-group mb-0">
    <%= f.submit(t('.action'), class: "btn btn-primary btn-block") %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<div class="page-header">
  <h4 class="page-title"><%= t('.title') %></h4>
  <h5 class="page-subtitle"><%= t('.subtitle') %></h5>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card card-body mb-3">
      <%= render("form", setting: @setting) %>
    </div>
  </div>
</div>